name: njtsign
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libffi=3.2.1
  - libgfortran=3.0.1
  - liblapack=3.8.0
  - libopenblas=0.3.6
  - ncurses=6.1
  - numpy=1.16.4
  - openblas=0.3.6
  - openssl=1.1.1c
  - pip=19.1.1
  - pyserial=3.4
  - python=3.7.3
  - readline=8.0
  - setuptools=41.0.1
  - sqlite=3.29.0
  - tk=8.6.9
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11

